export type Event = {
  id: string;
  title: string;
  thumbnail: string;
  category: string;
  date: string;
  time: string;
  viewers: number;
  description: string;
  videoUrl: string;
};

export const categories = ["All", "Gaming", "Music", "Tech", "Esports", "Talk Shows"];

export const mockEvents: Event[] = [
  {
    id: "evt-1",
    title: "Global Esports Championship Finals",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop",
    category: "Esports",
    date: "Oct 24, 2026",
    time: "18:00 EST",
    viewers: 145020,
    description: "Watch the thrilling conclusion of the Global Esports Championship as the top two teams battle for the grand prize.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-2",
    title: "Lofi Hip Hop Radio - Beats to Relax/Study to",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=2070&auto=format&fit=crop",
    category: "Music",
    date: "Live Now",
    time: "24/7",
    viewers: 32140,
    description: "A continuous live stream of lo-fi hip hop beats. Perfect background music for studying, working, or relaxing.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-3",
    title: "TechKeynote 2026: The Future of AI",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop",
    category: "Tech",
    date: "Nov 15, 2026",
    time: "10:00 PST",
    viewers: 85002,
    description: "Join the biggest tech innovators as they reveal next-generation AI breakthroughs and hardware advancements.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-4",
    title: "Speedrunning Classics Marathon",
    thumbnail: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=2165&auto=format&fit=crop",
    category: "Gaming",
    date: "Live Now",
    time: "14:00 GMT",
    viewers: 12400,
    description: "Top speedrunners gather to beat classic retro games as fast as possible for charity.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-5",
    title: "Late Night Tech Talk Show",
    thumbnail: "https://images.unsplash.com/photo-1516280440502-5c058bd8c6af?q=80&w=2070&auto=format&fit=crop",
    category: "Talk Shows",
    date: "Oct 25, 2026",
    time: "22:00 EST",
    viewers: 5400,
    description: "A casual late-night discussion covering the week's biggest tech news, gadget reviews, and viewer Q&A.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-6",
    title: "Indie Game Developer Showcase",
    thumbnail: "https://images.unsplash.com/photo-1556438064-2d7646166914?q=80&w=2070&auto=format&fit=crop",
    category: "Gaming",
    date: "Oct 28, 2026",
    time: "15:00 PST",
    viewers: 8900,
    description: "Discover the next big indie hits as developers showcase their upcoming games and chat with the community.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-7",
    title: "Electric Vibes Live Concert",
    thumbnail: "https://images.unsplash.com/photo-1470229722913-7c090b332f7f?q=80&w=2114&auto=format&fit=crop",
    category: "Music",
    date: "Nov 02, 2026",
    time: "20:00 GMT",
    viewers: 45000,
    description: "An immersive sensory live concert featuring top electronic music DJs with stunning visual effects.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-8",
    title: "Web3 & Blockchain Summit",
    thumbnail: "https://images.unsplash.com/photo-1639762681057-408e52192e55?q=80&w=2232&auto=format&fit=crop",
    category: "Tech",
    date: "Dec 05, 2026",
    time: "09:00 EST",
    viewers: 12500,
    description: "Experts discuss the future of decentralized finance, smart contracts, and Web3 applications.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-9",
    title: "FPS Pro League Qualifiers",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop",
    category: "Esports",
    date: "Nov 10, 2026",
    time: "17:00 CET",
    viewers: 67320,
    description: "Watch the intense qualifier rounds as teams fight for a spot in next year's pro league.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-10",
    title: "Coding with Chat: Building a React App",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
    category: "Tech",
    date: "Live Now",
    time: "11:00 EST",
    viewers: 3200,
    description: "Interactive live coding session where we build a full-stack React application from scratch with viewer input.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-11",
    title: "Acoustic Sunset Sessions",
    thumbnail: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?q=80&w=2070&auto=format&fit=crop",
    category: "Music",
    date: "Oct 30, 2026",
    time: "19:00 PST",
    viewers: 11200,
    description: "Relaxing acoustic guitar performances broadcasted live from a beautiful beachside sunset.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-12",
    title: "RPG World Premiere Gameplay",
    thumbnail: "https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=2119&auto=format&fit=crop",
    category: "Gaming",
    date: "Nov 20, 2026",
    time: "13:00 EST",
    viewers: 185000,
    description: "The exclusive first look at gameplay from the most anticipated role-playing game of the decade.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-13",
    title: "FGC Major Tournament",
    thumbnail: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=2070&auto=format&fit=crop",
    category: "Esports",
    date: "Dec 12, 2026",
    time: "12:00 PST",
    viewers: 94000,
    description: "The fighting game community gathers for the ultimate showdown. High stakes, incredible combos, and massive hype.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-14",
    title: "Podcast: The Creator Economy",
    thumbnail: "https://images.unsplash.com/photo-1559523161-0fc0d8b38a7a?q=80&w=2080&auto=format&fit=crop",
    category: "Talk Shows",
    date: "Nov 08, 2026",
    time: "16:00 GMT",
    viewers: 7600,
    description: "Top content creators discuss monetization, burnout, and the future of independent media.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  },
  {
    id: "evt-15",
    title: "Symphony Orchestra Live",
    thumbnail: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?q=80&w=2070&auto=format&fit=crop",
    category: "Music",
    date: "Dec 25, 2026",
    time: "20:00 EST",
    viewers: 22000,
    description: "A breathtaking performance by the National Symphony Orchestra performing holiday classics.",
    videoUrl: "https://www.youtube.com/embed/jfKfPfyJRdk",
  }
];
